### ISSUE TITLE
[Feature Request] Is it possible to leave a place for keywords that do not change when using a linter?

### ISSUE THREAD

**Issue by 1qzhworld** [northword/zotero-format-metadata#225] opened 2024-09-17 00:46 UTC
### Describe the feature

Is it possible to leave a place such that some words are protected and do not change when using a linter, or to replace a word with another when using a linter?

### Additional context

When I using linter for a batch of references, the title hand date are changed. However, I found that the proper noun is changed to lowercase. For example, in my case, the `Byzantine` in the title changed to `byzantine`. But this is not what I want.

**Comment by northword** [comment] 2024-09-17 00:57
duplicate of #58 ？

**Closed** 2024-09-24 15:55 UTC
Labels: enhancement
