### ISSUE TITLE
[Feature Request] Sentence Case to Title Case

### ISSUE THREAD

**Issue by notonthat** [northword/zotero-format-metadata#172] opened 2024-04-02 19:11 UTC
### Describe the feature

Can we get a right click menu option to change sentence case to title case? Thank you

**Comment by northword** [comment] 2024-04-03 01:18
Not plan, duplicate of #165 .

Also, right click on the title and the content menu has a zotero built in to title case conversion

**Closed** 2024-04-03 01:18 UTC
Labels: duplicate

**Comment by notonthat** [comment] 2024-04-03 23:42
> Not plan, duplicate of #165 .
> 
> Also, right click on the title and the content menu has a zotero built in to title case conversion

Zotero only allows you to do this for a single title at a time -- whereas your extension has the ability to convert the title on multiple selected files, which would be a very handy feature for those of us that prefer title case over sentence case. 

While I hope the plan changes to include this feature, just wanted to say I appreciate the response. Thank you.
